#!/usr/bin/env python
#coding=utf-8

from string import Template

#tree_name = "Summary/tree"
tree_name = "ZeeAnalyzer/tree"
title = ""
stats = 0

variable_dictionary = {
        "ZMass": {
            "formula": Template("ZMass$flavour"),
            "first_bin": 40,
            "last_bin": 140,
            "bin_width": 2, 
            "logy": False,
            "xtitle": "M_{e^{+}e^{-}} #[]{GeV/c^{2}}",
            "ytitle": "entries / #[]{{{0:.1f} GeV/c^{{2}}}}".format(2),
            },
        "ele2Calo": {
            "formula": Template("ele2Calo$flavour"),
            "first_bin": 0,
            "last_bin": 180,
            "bin_width": 1, 
            "logy": True,
            "xtitle": "ECAL Energy #[]{GeV/c^{2}}",
            "ytitle": "entries / #[]{{{0:.1f} GeV/c^{{2}}}}".format(1),
            },
        "ele2Pt": {
            "formula": Template("ele2Pt$flavour"),
            "first_bin": 0,
            "last_bin": 50,
            "bin_width": 1, 
            "logy": True,
            "xtitle": "p_{t} #[]{GeV/c}",
            "ytitle": "entries / #[]{{{0:.1f} GeV/c}}".format(1),
            },
        "ele2Eta": {
            "formula": Template("ele2Eta$flavour"),
            "first_bin": -3,
            "last_bin": 3,
            "bin_width": 0.2,
            "logy": False,
            "xtitle": "#eta",
            "ytitle": "entries / #[]{{{0:.1f}}}".format(0.2),
            },
        "ele2Phi": {
            "formula": Template("ele2Phi$flavour"),
            "first_bin": -3.2,
            "last_bin": 3.2,
            "bin_width": 0.3,
            "logy": True,
            "xtitle": "#phi",
            "ytitle": "entries / #[]{{{0:.1f}}}".format(0.3),
            },
        "ele2FbremMode": {
            "formula": Template("ele2FbremMode$flavour"),
            "first_bin": 0,
            "last_bin": 1,
            "bin_width": 0.05,
            "xtitle": "f_{brem}",
            "ytitle": "entries / #[]{{{0:.2f}}}".format(0.05),
            },
        "ele2ID": {
            "formula": Template("ele2ID$flavour"),
            "first_bin": -0.1,
            "last_bin": 1,
            "bin_width": 0.05,
            "logy": True,
            "xtitle": "mva",
            "ytitle": "entries / #[]{{{0:.2f}}}".format(0.05),
            },
        "ele2IsoAbs": {
            "formula": Template("ele2Iso$flavour"),
            "first_bin": 0,
            "last_bin": 50,
            "bin_width": 1, 
            "logy": True,
            "xtitle": "#sum p_{t} #[]{GeV/c}",
            "ytitle": "entries / #[]{{{0:.1f} GeV/c}}".format(1),
            },
        "ele2NormalizedChi2": {
            "formula": Template("ele2Chi2$flavour / ele2Ndof$flavour"),
            "first_bin": 0,
            "last_bin": 5,
            "bin_width": 0.05, 
            "logy": True,
            "xtitle": "#chi^{2} / NDF",
            "ytitle": "entries / #[]{{{0:.2f}}}".format(0.05),
            },
        "ele2IsoRel": {
            "formula": Template("ele2Iso$flavour / ele2Pt$flavour"),
            "first_bin": 0,
            "last_bin": 0.3,
            "bin_width": 0.01, 
            "logy": True,
            "xtitle": "#sum p_{t} / p_{t}",
            "ytitle": "entries / #[]{{{0:.2f}}}".format(0.01),
            },
        "ele1Calo": {
            "formula": Template("ele1Calo$flavour"),
            "first_bin": 0,
            "last_bin": 180,
            "bin_width": 5, 
            "logy": True,
            "xtitle": "ECAL Energy #[]{GeV/c^{2}}",
            "ytitle": "entries / #[]{{{0:.0f} GeV/c^{{2}}}}".format(5),
            },
        "ele1Pt": {
            "formula": Template("ele1Pt$flavour"),
            "first_bin": 0,
            "last_bin": 50,
            "bin_width": 1, 
            "logy": False,
            "xtitle": "p_{t} #[]{GeV/c}",
            "ytitle": "entries / #[]{{{0:.0f} GeV/c}}".format(1),
            },
        "ele1Eta": {
            "formula": Template("ele1Eta$flavour"),
            "first_bin": -3,
            "last_bin": 3,
            "bin_width": 0.1,
            "logy": False,
            "xtitle": "#eta",
            "ytitle": "entries / #[]{{{0:.1f}}}".format(0.1),
            },
        "ele1Phi": {
            "formula": Template("ele1Phi$flavour"),
            "first_bin": -3.2,
            "last_bin": 3.2,
            "bin_width": 0.2,
            "logy": True,
            "xtitle": "#phi",
            "ytitle": "entries / #[]{{{0:.1f}}}".format(0.2),
            },
        "ele1FbremMode": {
            "formula": Template("ele1FbremMode$flavour"),
            "first_bin": 0,
            "last_bin": 1,
            "bin_width": 0.02,
            "logy": True,
            "xtitle": "f_{brem}",
            "ytitle": "entries / #[]{{{0:.2f}}}".format(0.02),
            },
        "ele1ID": {
            "formula": Template("ele1ID$flavour"),
            "first_bin": -0.1,
            "last_bin": 1,
            "bin_width": 0.02,
            "logy": False,
            "xtitle": "mva",
            "ytitle": "entries / #[]{{{0:.2f}}}".format(0.02),
            },
        "ele1IsoAbs": {
            "formula": Template("ele1Iso$flavour"),
            "first_bin": 0,
            "last_bin": 50,
            "bin_width": 1, 
            "logy": False,
            "xtitle": "#sum p_{t} #[]{GeV/c}",
            "ytitle": "entries / #[]{{{0:.1f} GeV/c}}".format(1),
            },
        "ele1NormalizedChi2": {
            "formula": Template("ele1Chi2$flavour / ele1Ndof$flavour"),
            "first_bin": 0,
            "last_bin": 5,
            "bin_width": 0.05, 
            "logy": True,
            "xtitle": "#chi^{2} / NDF",
            "ytitle": "entries / #[]{{{0:.2f}}}".format(0.05),
            },
        "ele1IsoRel": {
            "formula": Template("ele1Iso$flavour / ele1Pt$flavour"),
            "first_bin": 0,
            "last_bin": 0.3,
            "bin_width": 0.01, 
            "logy": False,
            "xtitle": "#sum p_{t} / p_{t}",
            "ytitle": "entries / #[]{{{0:.2f}}}".format(0.01),
            },
        }


lumi = 0.166909846
#lumi = 0.140707512

histogram_dictionary = {
        "Data": {
            "MarkerStyle": 20,
            "MarkerColor": 1,
            "legend": "Data #int Ldt = #[]{{{0:.1f} nb^{{-1}}}}".format(lumi * 1e3),
            "stack_order": 21
            },
        "Zee": {
            "LineColor": 2,
            "FillColor": 0,
            "cross_section": 970,
            "filter_efficiency": 1,
            "reco_efficiency" : 1,
            "legend": "Zee",
            "stack_order": 20,
            },
        "Ztautau": {
            "LineColor": 5,
            "FillColor": 5,
            "cross_section": 1300,
            "filter_efficiency": 1,
            "reco_efficiency" : 1,
            "legend": "Z#tau#tau",
            "stack_order": 1,
            },
        "TTbar": {
            "LineColor": 4,
            "FillColor": 4,
            "cross_section": 90,
            "filter_efficiency": 1,
            "reco_efficiency" : 1,
            "legend": "t#bar{t}",
            "stack_order": 2,
            },
        "Wenu": {
            "LineColor": 6,
            "FillColor": 6,
            "cross_section": 7899,
            "filter_efficiency": 0.779,
            "reco_efficiency" : 1,
            "legend": "W#rightarrow e#nu",
            "stack_order": 3,
            },
        "QCDEM2030": {
                "LineColor": 46,
                "FillColor": 46,
                "cross_section": 2.355e8,
                "filter_efficiency": 7.3e-3,
                "reco_efficiency" : 1,
                "legend": "QCD EM-enriched",
                "stack_order": 4,
                },
        "QCDEM3080": {
                "LineColor": 46,
                "FillColor": 46,
                "cross_section": 5.93e7,
                "filter_efficiency": 59e-3,
                "reco_efficiency": 1,
                "legend": "QCD EM-enriched",
                "stack_order": 5,
                },
        "QCDEM80170": {
                "LineColor": 46,
                "FillColor": 46,
                "cross_section": 9.06e5,
                "filter_efficiency": 148e-3,
                "reco_efficiency" : 1,
                "legend": "QCD EM-enriched",
                "stack_order": 5,
                },
        "BCtoE2030": {
                "LineColor": 32,
                "FillColor": 32,
                "cross_section": 2.355e8,
                "filter_efficiency": 0.46e-3,
                "reco_efficiency" : 1,
                "legend": "BC #rightarrow e",
                "stack_order": 6,
                },
        "BCtoE3080": {
                "LineColor": 32,
                "FillColor": 32,
                "cross_section": 5.93e7,
                "filter_efficiency": 2.43e-3,
                "reco_efficiency" : 1,
                "legend": "BC #rightarrow e",
                "stack_order": 7,
                },
        "BCtoE80170": {
                "LineColor": 32,
                "FillColor": 32,
                "cross_section": 9.06e5,
                "filter_efficiency": 10.3e-3,
                "reco_efficiency" : 1,
                "legend": "BC #rightarrow e",
                "stack_order": 8,
                },
        "PhotonJet015": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 8.446e7,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 9,
                },
        "PhotonJet1520": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 1.147e5,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 10,
                },
        "PhotonJet2030": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 5.718e4,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 11,
                },
        "PhotonJet3050": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 1.652e4,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 12,
                },
        "PhotonJet5080": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 2.723e3,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 13,
                },
        "PhotonJet80120": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 4.462e2,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 14,
                },
        "PhotonJet120170": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 84.43,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 15,
                },
        "PhotonJet170300": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 22.55,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 16,
                },
        "PhotonJet300500": {
                "LineColor": 1,
                "FillColor": 1,
                "cross_section": 1.545,
                "filter_efficiency": 1,
                "reco_efficiency" : 1,
                "legend": "#gamma+jet",
                "stack_order": 17,
                },
        }
