#!/usr/bin/env python
#coding=utf-8

from ROOT import TStyle

# style:
style = TStyle("MyStyle", "style for my ROOT graphs and histograms")
style.SetCanvasBorderMode(0)
style.SetCanvasColor(0)
#style.SetFillColor(0)
style.SetCanvasDefH(768)
style.SetCanvasDefW(1024)
style.SetCanvasDefX(0)
style.SetCanvasDefY(0)
style.SetPadBorderMode(0)
style.SetPadColor(0)
style.SetPadGridX(False)
style.SetPadGridY(False)
style.SetGridColor(0)
style.SetGridStyle(3)
style.SetGridWidth(1)
style.SetOptStat(1)
style.SetPadTickX(0)
style.SetPadTickY(0)
style.SetHistLineColor(1)
style.SetHistLineStyle(0)
style.SetHistLineWidth(2)
style.SetEndErrorSize(2)
style.SetErrorX(0)
style.SetOptStat(111111)
style.SetStatColor(0)
style.SetStripDecimals(0)
style.SetTitleColor(1, "XYZ")
style.SetTitleFillColor(0)
style.SetTitleFont(42, "XYZ")
style.SetTitleXOffset(1)
style.SetTitleYOffset(1)
style.SetLabelOffset(0.005, "XYZ")
style.SetLabelSize(0.045, "XYZ")
style.SetTitleSize(0.04, "XYZ")
style.SetTitleFont(22,"X")
style.SetTitleFont(22,"Y")
style.SetTitleFont(22,"Z")
style.SetPadBottomMargin(0.13)
style.SetPadLeftMargin(0.15)
style.SetMarkerStyle(21)
style.SetMarkerSize(1.3)

