#!/usr/bin/env python
#coding=utf-8

from ROOT import TStyle

# style:
ele_style = TStyle("eleStyle", "Style for electron validation")
ele_style.SetCanvasBorderMode(0)
ele_style.SetCanvasColor(0)
ele_style.SetFillColor(0)
ele_style.SetCanvasDefH(600)
ele_style.SetCanvasDefW(800)
ele_style.SetCanvasDefX(0)
ele_style.SetCanvasDefY(0)
ele_style.SetPadBorderMode(0)
ele_style.SetPadColor(0)
ele_style.SetPadGridX(False)
ele_style.SetPadGridY(False)
ele_style.SetGridColor(0)
ele_style.SetGridStyle(3)
ele_style.SetGridWidth(1)
ele_style.SetOptStat(1)
ele_style.SetPadTickX(1)
ele_style.SetPadTickY(1)
ele_style.SetHistLineColor(1)
ele_style.SetHistLineStyle(0)
ele_style.SetHistLineWidth(2)
ele_style.SetEndErrorSize(2)
ele_style.SetErrorX(0)
ele_style.SetOptStat(1)
ele_style.SetStatColor(0)
ele_style.SetStripDecimals(0)
ele_style.SetTitleColor(1, "XYZ")
ele_style.SetTitleFillColor(0)
ele_style.SetTitleFont(42, "XYZ")
ele_style.SetTitleXOffset(1)
ele_style.SetTitleYOffset(1)
ele_style.SetLabelOffset(0.005, "XYZ")
ele_style.SetTitleSize(0.05, "XYZ")
ele_style.SetTitleFont(22,"X")
ele_style.SetTitleFont(22,"Y")
ele_style.SetTitleFont(22,"Z")
ele_style.SetHistLineWidth(1)
ele_style.SetPadBottomMargin(0.13)
ele_style.SetPadLeftMargin(0.15)
#ele_style.SetMarkerStyle(21)
#ele_style.SetMarkerSize(0.8)
